export * from './Object1'
export * from './Object2'
export * from './Object3'
export * from './Object4'
export * from './Object5'
export * from './Object6'
export * from './Object7'
export * from './Object8'

export type ObjectId =
  | 'Object1'
  | 'Object2'
  | 'Object3'
  | 'Object4'
  | 'Object5'
  | 'Object6'
  | 'Object7'
  | 'Object8'